spring:
  datasource:
    url: ${HOSTED_DATABASE_URL}
    username: ${HOSTED_DATABASE_USERNAME}
    password: ${HOSTED_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # default_schema: hydropay

app:
  backup:
    directory: ${BACKUP_DIRECTORY:./backups}
    pg-dump-path: ${PG_DUMP_PATH:pg_dump}
    pg-restore-path: ${PG_RESTORE_PATH:pg_restore}
    psql-path: ${PSQL_PATH:psql}
    cron:
      secret-key: ${BACKUP_CRON_SECRET}
  cron-job-org:
    api-key: ${CRON_JOB_ORG_API_KEY:}
    job-id: ${CRON_JOB_ORG_BACKUP_JOB_ID:}
