spring:
  datasource:
    url: ${LOCAL_DATABASE_URL}?sslmode=disable
    username: ${LOCAL_DATABASE_USERNAME}
    password: ${LOCAL_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  backup:
    directory: ${BACKUP_DIRECTORY:./backups}
    pg-dump-path: ${PG_DUMP_PATH:pg_dump}
    psql-path: ${PSQL_PATH:psql}
    cron:
      secret-key: ${BACKUP_CRON_SECRET}
