spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

payhere:
  merchant_id: ${PAYHERE_MERCHANT_ID} 
  merchant_secret: ${PAYHERE_MERCHANT_SECRET}
  return_url: ${PAYHERE_RETURN_URL}
  cancel_url: ${PAYHERE_CANCEL_URL}
  notify_url: ${PAYHERE_NOTIFY_URL}

text-lk:
  api-token: ${TEXT_LK_API_TOKEN}
  sender-id: ${TEXT_LK_SENDER_ID}
  api-endpoint: ${TEXT_LK_API_ENDPOINT}


server:
  port: ${PORT:8081}

jwt:
  secret: ${JWT_SECRET}
  expiry-ms: ${JWT_EXPIRY_MS:86400000}

app:
  activation-token-expiry-hours: 72
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  super-admin:
    nic: ${SUPER_ADMIN_NIC}
    email: ${SUPER_ADMIN_EMAIL}
    password: ${SUPER_ADMIN_PASSWORD}
