spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hydropay_db
    username: hydropay_user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: hansanatlk4739@gmail.com
    password: necz snyh svgk xxce
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud_name: df87pqbem
  api_key: 626896215766676
  api_secret: eHUnG-RbDliFhdR-TkW9iPHrs6s

payhere:
  merchant_id: 1235108 
  merchant_secret: MTAxNTE4NTMzNjI4NDYyMTE3MDUxOTE3MjYxMjc3MzQ1MjgzOTY5Nw==
  return_url: http://localhost:8080/api/payments/success
  cancel_url: http://localhost:8080/api/payments/cancel
  notify_url: http://localhost:8080/api/payments/notifyalhost:8080/api/payments/notify


server:
  port: 8081
