spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

payhere:
  merchant_id: ${PAYHERE_MERCHANT_ID} 
  merchant_secret: ${PAYHERE_MERCHANT_SECRET}
  return_url: ${PAYHERE_RETURN_URL}
  cancel_url: ${PAYHERE_CANCEL_URL}
  notify_url: ${PAYHERE_NOTIFY_URL}


server:
  port: ${PORT:8081}